//* Root
export { default as Login } from './Login'
export { default as Dashboard } from './Dashboard'
export { default as EmployeeFiles } from './EmployeeFiles'
export { default as EmployeeEdit } from './EmployeeEdit'
export { default as TimeKeeping } from './TimeKeeping'
export { default as Leave } from './Leave'
export { default as Schedule } from './Schedule'
export { default as Tasks } from './Tasks'

//* System Settings
// Task Management
export { default as TasksSettings } from './system-settings/task-management/TasksSettings'
export { default as TaskActivities } from './system-settings/task-management/TaskActivities'
export { default as TaskTypes } from './system-settings/task-management/TaskTypes'
export { default as TaskSprint } from './system-settings/task-management/TaskSprint'

export { default as BankDetails } from './system-settings/BankDetails'
export { default as Client } from './system-settings/Client'
export { default as ClientBranch } from './system-settings/ClientBranch'
export { default as ClientBranchHoliday } from './system-settings/ClientBranchHoliday'
export { default as DailyRate } from './system-settings/DailyRate'
export { default as Department } from './system-settings/Department'
export { default as EmployeeStatus } from './system-settings/EmployeeStatus'
export { default as Expense } from './system-settings/Expense'
export { default as ExpenseType } from './system-settings/ExpenseType'
export { default as Holiday } from './system-settings/Holiday'
export { default as HolidayType } from './system-settings/HolidayType'
export { default as LeaveStatus } from './system-settings/LeaveStatus'
export { default as LeaveDuration } from './system-settings/LeaveDuration'
export { default as LeaveType } from './system-settings/LeaveType'
export { default as Position } from './system-settings/Position'
export { default as Role } from './system-settings/Role'
export { default as SalaryRate } from './system-settings/SalaryRate'


// Employee 201 Edit
export { default as EmployeeBenefits } from './employee-201/Benefits'
export { default as EmployeeClientHistory } from './employee-201/ClientHistory'
export { default as EmployeeClientSchedule } from './employee-201/ClientSchedule'
export { default as EmployeeContracts } from './employee-201/Contracts'
export { default as EmployeeDocuments } from './employee-201/EmployeeDocuments'
export { default as EmployeeEvaluations } from './employee-201/Evaluations'
export { default as EmployeeGovernmentDocuments } from './employee-201/GovernmentDocuments'
export { default as EmployeeLeaveCredits } from './employee-201/LeaveCredits'
export { default as EmployeeMemorandums } from './employee-201/Memorandums'
export { default as EmployeePayScheme } from './employee-201/PayScheme'
export { default as EmployeeSalary } from './employee-201/Salary'
export { default as EmployeeSalaryAdjustments } from './employee-201/SalaryAdjustments'
export { default as EmployeeSalaryHistory } from './employee-201/SalaryHistory'
export { default as EmployeeUserProfile } from './employee-201/UserProfile'
