export const BASE_URL = 'https://staging-hrportal.redcoresolutions.com/passthru/api/backend'
export const BASE_URL_BACKEND = 'https://staging-hrportal.redcoresolutions.com/backend'
export const BASE_URL_PASSTHRU = 'https://staging-hrportal.redcoresolutions.com/passthru/api'
export const BASE_URL_REPORT = 'https://staging-hrportal.redcoresolutions.com/report/api'
export const BASE_URL_SYSTEMLOGS = 'https://staging-hrportal.redcoresolutions.com/passthru/api/'